default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: antisocial_development
  host: localhost
  username: XXX
  port: 5432
  password: XXX

test:
  <<: *default
  database: antisocial_test

production:
  <<: *default
  database: antisocial_production
  username: antisocial
  password: <%= ENV['ANTISOCIAL_DATABASE_PASSWORD'] %>
